### ISSUE TITLE
Support for removing debuginfo and symbols

### ISSUE THREAD

**Issue by ankane** [oxidize-rb/cross-gem-action#112]
Hey,

I was wondering if there was a way for the action to support the [`strip`](https://doc.rust-lang.org/cargo/reference/profiles.html#strip) option, which can significantly reduce the binary size.

```toml
[profile.release]
strip = true
```

It currently fails on `x86_64-darwin` with:

```text
warning: stripping debug info with `strip` failed: exit status: 1
  |
  = note: strip: /home/runner/work/tokenizers-ruby/tokenizers-ruby/tmp/x86_64-darwin/tokenizers/3.1.0/target/x86_64-apple-darwin/release/deps/libtokenizers.dylib: file format not recognized
```

**Comment by ankane** [comment]
It looks like `strip` is [hard-coded](https://github.com/rust-lang/rust/blob/657eefe2dcf18f76ac67a39945810128e101178c/compiler/rustc_codegen_ssa/src/back/link.rs#L1013), but creating a symlink in `setup` works.

```yml
    strategy:
      matrix:
        include:
          - platform: x86_64-darwin
            setup: sudo ln -s /opt/osxcross/target/bin/x86_64-apple-darwin-strip /usr/local/bin/strip
    steps:
      - uses: oxidize-rb/cross-gem-action@v7
        with:
          platform: ${{ matrix.platform }}
          setup: |
            bundle install
            ${{ matrix.setup }}
```
